#!/bin/bash

threads=20
tseed=$(($(date +%s%N)/1000000-1393400000000))
data="sim_data"

start_time=$(date +%s)
waitForMe (){
    while : 
    do 
	activth=$(ps aux | grep "[e]icdirc" | wc -l)
	printf "\r$statusline [$theta deg] [$activth jobs] ---- [$(($(date +%s) - start_time)) s] "
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
	sleep 1
    done
}


for theta in $(seq 25 5 155); do
    ../../build/eicdirc -r 4 -i $data/hits.$theta.root -trackingres 0.0005 -timeres 0.1 -timecut 0.2 -e 5000 -v 2 -b 1  > $data/h_b$i.$theta.2.log &
    waitForMe $threads    
done

