# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.


# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit

# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"

# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "50 MeV"  "/gun/energy 50 MeV"
/gui/addButton gun "1 GeV"   "/gun/energy 1 GeV"
/gui/addButton gun "10 GeV"  "/gun/energy 10 GeV"
/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "pi0"     "/gun/particle pi0"
/gui/addButton gun "pi+"     "/gun/particle pi+"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"

# Field menu :
/gui/addMenu field Field
/gui/addButton field "off"       "/B2/det/setField 0.2 tesla"
/gui/addButton field "0.2 tesla" "/B2/det/setField 0.2 tesla"
/gui/addButton field "2.0 tesla" "/B2/det/setField 2.0 tesla"

# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Side" "/vis/drawView -90 90.000001"
/gui/addButton viewer "Top" "/vis/drawView 90"
/gui/addButton viewer "Front" "/vis/drawView 0"
/gui/addButton viewer "Expansion Volume" "/control/execute vis_side.mac"
