#!/bin/bash

# for i in {1..20}; do
#     ../build/eicdirc -s 1 -o ../data/lut_d$i.root -x "opticalphoton" -p "3.18 eV" -w 0 -g 1 -h 11 -e 500000 -c 3 -l 3 -d 0 -t $i -b 1 &
# done

# for i in {1..10}; do
#     ../build/eicdirc -s 1 -o ../data/lut_d$i.root -x "opticalphoton" -p "3.18 eV" -w 0 -g 1 -h 11 -e 500000 -c 4 -l 3 -d 0 -r $i -b 1 &
# done

#../build/eicdirc -s 1 -o ../data/lut.root -x "opticalphoton" -p "3.18 eV" -w 0 -g 1 -h 11 -e 5000000 -c 3 -l 3 -d 0 -r 12341234 -b 1 &


simopt="-p 6 -w 0 -g 1 -h 11 -c 4 -l 3 -z 0 -v 0 -zpos 1 -ev 1 -b 1"

for id in `LANG=en_us seq 700 25 1200`; do
   ../build/eicdirc -o ../data/l_b_${id}.root -s 1 ${simopt} -t1 ${id} -x "opticalphoton" -p "3.18 eV"  -e 10000000 &
done

    
