#!/bin/bash

if [ ${1} == "" ]; then
    nthreads=6
else
    nthreads=${1}
fi

if [ ${2} == "" ]; then
    nsteps=2
else
    nsteps=${2}
fi

if [ ${3} == "" ]; then
    run=0
else
    run=${3}
fi


tseed=$(($(date +%s%N)/1000000-1393400000000))
printf "====== Run EICDIRC with $tseed seed base ======\n"

#./eicdirc -s 1 -a 60 -x "opticalphoton" -p "3.18 eV" -w 0 -g 1 -h 11 -e 500000 -c 3 -l 3 -d 0 -b 1


waitForMe (){
    i=0    
    while : 
    do
	activth=$(ps aux | grep "[e]icdirc" | grep "h_b" | wc -l)

	printf "\r$statusline "
	printf '%0.s-' $(seq 1 $activth)
	sleep .1
	
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
    done
}  

if [ ${run} != "2" ]; then
    mkdir -p hdata
    start_time=$(date +%s)
    statusline="GSim"
    for i in $(eval echo {30..150..${nsteps}}); do 
	../build/eicdirc -r $tseed$i -o hdata/h_b$i.root -s 0 -a $i -x "pi+" -p 6  -w 0 -g 1 -h 11 -e 10 -c 3 -l 3 -b 1  > /dev/null  &
	waitForMe $nthreads
    done
    waitForMe "1"
    finish_time=$(date +%s)
    printf "\r$statusline --- done [$((finish_time - start_time)) s]\n"
fi


start_time=$(date +%s)
statusline="Reco"
for i in $(eval echo {30..150..$nsteps}); do 
    ../build/eicdirc -i hdata/h_b$i.root -o r_b$i.root -s 2 > /dev/null 2> /dev/null &
    waitForMe $nthreads "reconstructions in process "
done
waitForMe "1"
finish_time=$(date +%s)
printf "\r$statusline --- done [$((finish_time - start_time)) s]\n"

sleep 2

statusline="$statusline merging .."

rm r_spr.root
hadd r_spr.root r_b*_spr.root

rm r_b*.root 


