#!/bin/bash

threads=20
tseed=$(($(date +%s%N)/1000000-1393400000000))

start_time=$(date +%s)
waitForMe (){
    while : 
    do 
	activth=$(ps aux | grep "[e]icdirc" | wc -l)
	printf "\r$statusline [$activth] ---- [$(($(date +%s) - start_time)) s] "
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
	sleep 1
    done
}

rm h_b*.root 
rm l_b*.log

tseed=$(($(date +%s%N)/1000000-1393400000000))

echo $tseed

# #LUT
# ../build/eicdirc -r 1 $args -o lut.root \
# 		 -theta 30 -x mix_pik -w 0 -g 1 -c 2031 -l 3 -ev 0 \
# 		 -x "opticalphoton" -p "3.18 eV"  -e 1000000 -b 1
# root -b -q lutmean.C'("lut.root")'

# for i in {0..9}; do
#     ../build/eicdirc -r 1 -o ../data/lut.$i.root -phi 99$i -e 15000000 -b 1 &
# done
# waitForMe 1
# for i in {0..9}; do
#     root -b -q loadlib.C lutmean.C"(\"../data/lut.$i.root\")" &
# done


# for i in $(seq 163.5 0.5 167.5) ; do
#     ../build/eicdirc -r 0 -seed $tseed -o hdata/h_b$i.root -field 2 -p 6 -theta $i -phi 995 -e 100 -b 1 &
#     waitForMe $threads
# done



for i in {0..19}; do
    ../build/eicdirc -r 0 -seed $tseed$i -o h_b$i.root -p 6 -theta 30 -e 250 -b 1 -x pi+ -field 0 -phi 995 &
    # ../build/eicdirc -r 0 -seed $tseed$i -o h_b$i.root -x mix_pik -theta 30 -e 100 -b 1 &
    # ../build/eicdirc -r 0 -seed $tseed$i -o h_b$i.root -x mix_pik \
    # 		     -theta 30 -field 0 -e 150 -b 1 -dn 116640000 & 
done

#reco
# ../build/eicdirc -r 2 -i sim.root -u lut.avr.root -trackingres 0.0005 -timeres 0.1 -timecut 0.2 -e 1000 -v 3

waitForMe 1
sleep 1

hadd -f sim.root h_b*.root
