#!/bin/bash

rm h_b*.root 
rm l_b*.log

tseed=$(($(date +%s%N)/1000000-1393400000000))

echo $tseed

#for i in {0..9}; do ../build/eicdirc -r $tseed$i -o h_b$i.root -s 0 -a 30 -x "mix_pik" -p 6  -w 0 -g 1 -h 11 -e 8000 -c 4 -l 100 -b 1  > l_b$i.log & done
#for i in {0..9}; do ../build/eicdirc -r $tseed$i -o h_b$i.root  -s 0 -a 30 -x "pi+" -p 6 -w 0 -g 1 -h 11 -l 3 -c 4 -e 0 -d 0 -e 200 -b 1  > l_b$i.log & done
#for i in {0..9}; do ../build/eicdirc -r $tseed$i -o h_b$i.root  -s 0 -a 30 -x "pi+" -p 6 -w 0 -g 1 -h 1 -l 6 -c 4 -e 0 -d 0 -e 200 -b 1  > l_b$i.log & done
#for i in {0..9}; do ../build/eicdirc -r $tseed$i -o h_b$i.root  -s 0 -a 30 -x "pi+" -p 6 -w 0 -g 3 -h 11 -l 0 -c 4 -e 0 -d 0 -e 200 -b 1  > l_b$i.log & done
#for i in {0..9}; do ../build/eicdirc -r $tseed$i -o h_b$i.root  -s 0 -a 30 -x "pi+" -p 6 -w 0 -g 3 -h 11 -l 6 -c 4 -e 0 -d 0 -e 200 -b 1  > l_b$i.log & done
#for i in {0..9}; do ../build/eicdirc -r $tseed$i -o h_b$i.root  -s 0 -a 30 -x "pi+" -p 6 -w 0 -g 1 -h 1 -l 3 -c 4 -e 0 -d 0 -e 200 -b 1  > l_b$i.log & done
for i in {0..9}; do ../build/eicdirc -r $tseed$i -o h_b$i.root  -s 0 -a 30 -x "pi+" -p 6 -w 0 -g 3 -h 11 -l 6 -c 4 -e 0 -d 0 -e 100 -b 1  > l_b$i.log & done

sleep 1

while : 
do
    activth=$(ps aux | grep "[e]icdirc" | grep "h_b" | wc -l)
    diffth=$(($maxnthr-$activth))
    echo "We have $activth active eicdirc simulations " 
    if [ "$activth" -eq 0 ]; then 
      break  
    fi
    sleep 2
done

sleep 2
 
rm hits.root
hadd hits.root h_b*.root
