#!/bin/bash

rm h_b*.root 
rm l_b*.log

tseed=$(($(date +%s%N)/1000000-1393400000000))

echo $tseed

#overlay
#for i in {1..4}; do ../build/eicdirc -r $tseed$i -o h_b$i.root  -s 0 -a 90 -x "mix_pie" -p 10.0 -w 0 -h 11 -c 4 -l 3 -z 0 -v 0 -zpos 1 -g 1 -ev 1 -t1 900 -t2 16 -e 200 -b 1  > l_b$i.log & done

# for i in {1..4}; do ../build/eicdirc -r $tseed$i -o h_b$i.root  -s 0 -a 30 -x "mix_pie" -p 1.0 -w 0 -h 11 -c 4 -l 3 -z 0.01 -v 0 -zpos 1 -g 1 -ev 0 -e 400 -b 1  > l_b$i.log & done


# phi scan
# for i in `LANG=en_us seq 0 0.001 0.032`; do
#     ../build/eicdirc -r $tseed$i -o h_b$i.root  -s 0 -a 90 -x "mu-" -p 10.0 -w 0 -h 11 -c 4 -l 3 -z 0 -v 0 -zpos 1 -g 1 -ev 1 -t1 $i -e 1000 -b 1  > l_b$i.log & 
# done

# for i in `LANG=en_us seq 0 0.0002 0.004`; do
#     # ../build/eicdirc -r $tseed$i -o h_b$i.root  -s 0 -a 30 -x "mix_pie" -p 1.0 -w 0 -h 11 -c 4 -l 3 -z $i -v 0 -zpos 1 -g 1 -ev 0 -e 2000 -b 1  > l_b$i.log &

#     ../build/eicdirc -o res_pimu_tr_$i.root -s 2 -i hits_pimu.root -u ../data/lut_avr.root -s 2 -tc 0.2 -t1 $i -v 2  &
# done



# for i in {0..9}; do ../build/eicdirc -seed $tseed$i -o h_8b$i.root  -theta 30 -w 0 -g 1 -c 2038 -l 3 -t3 5 -x mix_pik -e 1 -w 0 -e 500 -b 1  > l_8b$i.log & done
# for i in {0..9}; do ../build/eicdirc -seed $tseed$i -o h_1b$i.root  -theta 30 -w 0 -g 1 -c 2031 -l 3 -t3 5 -x mix_pik -e 1 -w 0 -e 500 -b 1  > l_1b$i.log & done

for i in {0..24}; do ../build/eicdirc -seed $tseed$i -o h_b$i.root  -theta 30 -w 0 -g 1 -c 2031 -l 3 -x mix_pie -w 0 -e 200 -trackres 0.0022 -b 1 > l_b$i.log & done

sleep 1

while : 
do
    activth=$(ps aux | grep "[e]icdirc" | grep "h_" | wc -l)
    diffth=$(($maxnthr-$activth))
    echo "We have $activth active eicdirc simulations " 
    if [ "$activth" -eq 0 ]; then 
      break  
    fi
    sleep 2
done

sleep 2

hadd -f hgen_pie_ns00.root h_b*.root
